# Generated by Django 6.0.3 on 2026-04-03 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultivo',
            name='region',
            field=models.CharField(blank=True, choices=[('andina', 'Región Andina'), ('caribe', 'Región Caribe'), ('pacifica', 'Región Pacífica'), ('orinoquia', 'Región Orinoquía'), ('amazonia', 'Región Amazonía'), ('insular', 'Región Insular')], max_length=50, null=True),
        ),
    ]
