# Generated by Django 6.0.3 on 2026-04-03 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_cultivo_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultivo',
            name='altura_maxima',
            field=models.IntegerField(blank=True, help_text='Metros sobre el nivel del mar', null=True),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='altura_minima',
            field=models.IntegerField(blank=True, help_text='Metros sobre el nivel del mar', null=True),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='clima',
            field=models.CharField(blank=True, choices=[('calido', 'Cálido'), ('templado', 'Templado'), ('frio', 'Frío'), ('paramo', 'Páramo')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='rendimiento_ha',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Toneladas por hectárea', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='temporada',
            field=models.CharField(blank=True, choices=[('enero-marzo', 'Enero - Marzo'), ('abril-junio', 'Abril - Junio'), ('julio-septiembre', 'Julio - Septiembre'), ('octubre-diciembre', 'Octubre - Diciembre'), ('todo-el-año', 'Todo el año')], max_length=50, null=True),
        ),
    ]
