# Generated by Django 6.0.3 on 2026-04-04 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_cultivo_altura_maxima_cultivo_altura_minima_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suelo',
            name='cultivos_recomendados',
            field=models.TextField(blank=True, help_text='Cultivos que crecen bien en este suelo', null=True),
        ),
        migrations.AddField(
            model_name='suelo',
            name='drenaje',
            field=models.CharField(blank=True, help_text='Ej: Bueno, Moderado, Deficiente', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='suelo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='suelos/'),
        ),
        migrations.AddField(
            model_name='suelo',
            name='ph',
            field=models.CharField(blank=True, choices=[('acido', 'Ácido (< 6.0)'), ('neutro', 'Neutro (6.0 - 7.0)'), ('alcalino', 'Alcalino (> 7.0)')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='suelo',
            name='tipo',
            field=models.CharField(blank=True, choices=[('arcilloso', 'Arcilloso'), ('arenoso', 'Arenoso'), ('limoso', 'Limoso'), ('franco', 'Franco'), ('mixto', 'Mixto'), ('organico', 'Orgánico')], max_length=50, null=True),
        ),
    ]
